### PR TITLE
AES round function diagram

### PR DESCRIPTION
**Pull request by tarcieri**
Image trace of the diagram originally from the Rijndael web site

AES Round Function

### CODE REVIEW

**Comment by newpavlov** [comment]
Do you plan to add it to the `aes` docs or README? I am not sure if it's worth doing it, since for most users the image probably will be quite confusing.

**Comment by tarcieri** [comment]
That was the plan: replacing the current SBox illustration.

I think it's more representative of how AES / Rinjdael work than the current illustration.

**Comment by newpavlov** [comment]
Well, there is also an option of not having an image at all. :) Nevertheless, I am fine with this change if you would like to do it.

**Comment by tarcieri** [comment]
I think the diagrams are a nice touch, even if they don't provide a perfect at-a-glance view of how the algorithms operate.

Looking at this diagram, I think it might be nice to add some color similar to the current diagram before merging though.

**Comment by tarcieri** [comment]
Went ahead and added some color and I think it "pops" a little more now.

FWIW, found a couple other cool-looking diagrams here:

https://www.eng.tau.ac.il/~yash/crypto-netsec/rijndael.htm

Screen Shot 2021-04-15 at 2 33 54 PM
Screen Shot 2021-04-15 at 2 34 02 PM

**Pull request merged**
