### PR TITLE
Add elliptic-curve type transformations diagram

### PR DESCRIPTION
**Pull request by daviddrysdale**
Exported from:
https://docs.google.com/drawings/d/1bW4yUVvHV8Y_XMr8RC3CHfCGOhPFvtZL54JRvfeCHFo/preview
also known as:
https://tinyurl.com/rust-elliptic-curve-types

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Hmm, it would be better to get rid of the redirects via www.google.com&hellip;

**Comment by tarcieri** [comment]
Thanks!

**Comment by tarcieri** [comment]
Now live on https://docs.rs:

https://docs.rs/elliptic-curve/latest/elliptic_curve/#type-conversions

**Comment by newpavlov** [comment]
Unfortunately, the box links do not work with SVG embedded into a page for some reason. Also I think it may be worth to add a legend with box color descriptions.

**Comment by daviddrysdale** [comment]
> Unfortunately, the box links do not work with SVG embedded into a page for some reason. 

On a quick investigate, it looks like:
- Internal links don't work for an SVG file included into an HTML page via `` (as `rustdoc` emits here)
- Internal links *do* work for an SVG file included via `<object>`, but only if the target is same origin
- However, `rustdoc` [doesn't currently](https://github.com/rust-lang/rust/issues/32104) include any mechanism that allows media files to be included in the output.

So the nearest I can think of is to have the whole diagram link to loading the SVG as a page on its own.

However, that still doesn't seem to quite work for me: browsers displaying the [SVG file standalone](https://raw.githubusercontent.com/RustCrypto/media/master/img/elliptic-curve/type-transforms.svg) seem to indicate that there's links to follow (cursor changes), but a single click doesn't follow those links (although Command-clicking does load the destination in a new tab).

(I also tried putting a minimal wrapper HTML file into `media/img/elliptic-curve/` as the destination of the main image link, but raw.githubusercontent.com won't serve it as HTML.)

> Also I think it may be worth to add a legend with box color descriptions.

Added in #7

**Pull request merged**
