### PR TITLE
Add encryption and decryption images for block modes

### PR DESCRIPTION
**Pull request by newpavlov**
The images in this PR are manually created from scratch (using the [wikipedia images](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) for reference) and licensed under CC-BY 4.0.

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]

**Comment by newpavlov** [comment]
@tarcieri 
Do you know if it's possible to set a background color for an image tag? On the dark theme (which I use) such images are indiscernible. Ideally I would like to keep SVG image as-is without editing them. `style = "background-color: white;"` does not work.

**Comment by tarcieri** [comment]
I mainly edit vector graphics with Illustrator. I can add a white background in that. Perhaps if I do one we can see how to do it for the others (effectively just adding a white rectangle at the lowest z-offset)

**Comment by tarcieri** [comment]
Wow, Illustrator hates those SVGs and mangles them.

I think you can add something to the effect of:

```xml
<rect width="601" height="242" style="fill:#fff"/>
```

...somewhere close to the top, e.g. right before the `<text>`

**Comment by newpavlov** [comment]
There is a neat way of solving this issue by using `@media (prefers-color-scheme: light/dark) { .. }` to modify styles depending on user settings which should work for SVGs as well. Unfortunately, it looks like this property is currently broken on Firefox (at least on Linux). Setting `ui.systemUsesDarkTheme` to `1` and even toggling light/dark mode in the inspector has no effect on rendering, for some reason Firefox always uses the "light" styles.

UPD: In Chromium everything works as expected after launching it with `--enable-features=WebUIDarkMode --force-dark-mode` flags.
UPD2: Ah, it looks like in Firefox enabled `privacy.resistFingerprinting` causes browser to always choose the "light" styles. Disabling it "fixes" the rendering issue. I have filled this bugzilla request: https://bugzilla.mozilla.org/show_bug.cgi?id=1705930

**Comment by newpavlov** [comment]
I have replaced the wikipedia images with images manually created from scratch. Not only it significantly improves size, but also using the `@media` selector they are now dark mode friendly. I have confirmed in Firefox and Chrome that they indeed work correctly while being embedded into other pages.

**Pull request merged**
